# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`MooseX-WhatTheTrig`
	:runtime-requirement    [ :on "perl 5.008008"^^:CpanId ];
	:runtime-requirement    [ :on "Moose 2.0600"^^:CpanId ];
	:runtime-requirement    [ :on "Scope::Guard"^^:CpanId ];
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:test-requirement       [ :on "Test::Moose"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt 0.001"^^:CpanId ];
	.

